# Define constant variables for cell types
B_CELL = 'B Cell'
PLASMA_CELL = 'Plasma Cell'
MONOCYTE = 'Monocyte'
DENDRITIC_CELL = 'Dendritic Cell'
ENDOTHELIAL = 'Endothelial Cell'
ERYTHROID_LINEAGE = 'Erythroid Lineage Cell'
FIBROBLAST = 'Fibroblast'
GRANULOCYTE = 'Granulocyte'
NK_CELL = 'Natural Killer Cell'
T_CELL = 'T Cell'
NEURON = 'Neuron'
SATELLITE = 'Satellite Cell'
SKELETAL_MUSCLE = 'Skeletal Muscle Cell'
SMOOOTH_MUSCLE = 'Smooth Muscle Cell'
GLIAL_CELL = 'Glial Cell'
EPITHELIAL_CELL = 'Epithelial Cell'
MACROPHAGE = 'Macrophage'
CONNECTIVE_TISSUE_CELL = 'Connective Tissue Cell'
MISCELLANEOUS = 'Miscellaneous'

# Create the dictionary with variable constants as values
CELL_TYPES_DICT = {
    'acinar cell': EPITHELIAL_CELL,
    'activated type II NK T cell': NK_CELL,
    'adventitial cell': MISCELLANEOUS,
    'alternatively activated macrophage': MACROPHAGE,
    'alveolar macrophage': MACROPHAGE,
    'alveolar type 1 fibroblast cell': FIBROBLAST,
    'alveolar type 2 fibroblast cell': FIBROBLAST,
    'astrocyte': GLIAL_CELL,
    'astrocyte of the cerebral cortex': GLIAL_CELL,
    'B cell': B_CELL,
    'B-1 B cell': B_CELL,
    'B-2 B cell': B_CELL,
    'basal cell': EPITHELIAL_CELL,
    'basophil': GRANULOCYTE,
    'blood vessel endothelial cell': ENDOTHELIAL,
    'bronchial goblet cell': EPITHELIAL_CELL,
    'bronchial smooth muscle cell': SMOOOTH_MUSCLE,
    'bronchus fibroblast of lung': FIBROBLAST,
    'brush cell of trachebronchial tree': EPITHELIAL_CELL,
    'capillary endothelial cell': ENDOTHELIAL,
    'caudal ganglionic eminence derived GABAergic cortical interneuron': NEURON,
    'CD14-low, CD16-positive monocyte': MONOCYTE,
    'CD14-positive monocyte': MONOCYTE,
    'CD141-positive myeloid dendritic cell': DENDRITIC_CELL,
    'CD16-negative, CD56-bright natural killer cell, human': NK_CELL,
    'CD16-positive, CD56-dim natural killer cell, human': NK_CELL,
    'CD1c-positive myeloid dendritic cell': DENDRITIC_CELL,
    'CD4-positive helper T cell': T_CELL,
    'CD4-positive, alpha-beta cytotoxic T cell': T_CELL,
    'CD4-positive, alpha-beta memory T cell': T_CELL,
    'CD4-positive, alpha-beta T cell': T_CELL,
    'CD4-positive, CD25-positive, alpha-beta regulatory T cell': T_CELL,
    'CD8-alpha-alpha-positive, alpha-beta intraepithelial T cell': T_CELL,
    'CD8-positive, alpha-beta cytokine secreting effector T cell': T_CELL,
    'CD8-positive, alpha-beta cytotoxic T cell': T_CELL,
    'CD8-positive, alpha-beta memory T cell': T_CELL,
    'CD8-positive, alpha-beta T cell': T_CELL,
    'cell of skeletal muscle': SKELETAL_MUSCLE,
    'central memory CD4-positive, alpha-beta T cell': T_CELL,
    'cerebral cortex endothelial cell': ENDOTHELIAL,
    'chandelier pvalb GABAergic cortical interneuron': NEURON,
    'chromaffin cell': MISCELLANEOUS,
    'ciliated columnar cell of tracheobronchial tree': EPITHELIAL_CELL,
    'class switched memory B cell': B_CELL,
    'classical monocyte': MONOCYTE,
    'club cell': MISCELLANEOUS,
    'collagen secreting cell': MISCELLANEOUS,
    'columnar/cuboidal epithelial cell': EPITHELIAL_CELL,
    'common dendritic progenitor': DENDRITIC_CELL,
    'common myeloid progenitor': MISCELLANEOUS,
    'conventional dendritic cell': DENDRITIC_CELL,
    'cord blood hematopoietic stem cell': MISCELLANEOUS,
    'corticothalamic-projecting glutamatergic cortical neuron': NEURON,
    'cytotoxic T cell': T_CELL,
    'decidual natural killer cell, human': NK_CELL,
    'dendritic cell': DENDRITIC_CELL,
    'double negative T regulatory cell': T_CELL,
    'double negative thymocyte': MISCELLANEOUS,
    'double-positive, alpha-beta thymocyte': MISCELLANEOUS,
    'early lymphoid progenitor': MISCELLANEOUS,
    'effector CD4-positive, alpha-beta T cell': T_CELL,
    'effector CD8-positive, alpha-beta T cell': T_CELL,
    'effector memory CD4-positive, alpha-beta T cell': T_CELL,
    'effector memory CD8-positive, alpha-beta T cell': T_CELL,
    'elicited macrophage': MACROPHAGE,
    'embryonic stem cell': MISCELLANEOUS,
    'endocrine cell': MISCELLANEOUS,
    'endothelial cell': ENDOTHELIAL,
    'endothelial cell of artery': ENDOTHELIAL,
    'endothelial cell of lymphatic vessel': ENDOTHELIAL,
    'endothelial cell of vascular tree': ENDOTHELIAL,
    'endothelial cell of venule': ENDOTHELIAL,
    'enteric neuron': NEURON,
    'enterocyte': EPITHELIAL_CELL,
    'epithelial cell': EPITHELIAL_CELL,
    'epithelial cell of alveolus of lung': EPITHELIAL_CELL,
    'epithelial cell of exocrine pancreas': EPITHELIAL_CELL,
    'epithelial cell of lower respiratory tract': EPITHELIAL_CELL,
    'epithelial cell of nephron': EPITHELIAL_CELL,
    'epithelial cell of proximal tubule': EPITHELIAL_CELL,
    'epithelial cell of proximal tubule segment 1': EPITHELIAL_CELL,
    'epithelial cell of proximal tubule segment 3': EPITHELIAL_CELL,
    'erythroblast': ERYTHROID_LINEAGE,
    'erythrocyte': ERYTHROID_LINEAGE,
    'erythroid lineage cell': ERYTHROID_LINEAGE,
    'erythroid progenitor cell': ERYTHROID_LINEAGE,
    'eurydendroid cell': MISCELLANEOUS,
    'extravillous trophoblast': MISCELLANEOUS,
    'fat cell': MISCELLANEOUS,
    'fibroblast': FIBROBLAST,
    'fraction A pre-pro B cell': B_CELL,
    'gamma-delta T cell': T_CELL,
    'glial cell': GLIAL_CELL,
    'glomerular capillary endothelial cell': ENDOTHELIAL,
    'goblet cell': EPITHELIAL_CELL,
    'granulocyte': GRANULOCYTE,
    'granulocyte monocyte progenitor cell': MISCELLANEOUS,
    'group 2 innate lymphoid cell': MISCELLANEOUS,
    'group 3 innate lymphoid cell': MISCELLANEOUS,
    'group 3 innate lymphoid cell, human': MISCELLANEOUS,
    'helper T cell': T_CELL,
    'hematopoietic multipotent progenitor cell': MISCELLANEOUS,
    'hematopoietic stem cell': MISCELLANEOUS,
    'hepatocyte': MISCELLANEOUS,
    'Hofbauer cell': MISCELLANEOUS,
    'IgA plasma cell': PLASMA_CELL,
    'IgG plasma cell': PLASMA_CELL,
    'immature B cell': B_CELL,
    'innate lymphoid cell': MISCELLANEOUS,
    'intermediate monocyte': MONOCYTE,
    'interstitial cell of Cajal': MISCELLANEOUS,
    'intestinal epithelial cell': EPITHELIAL_CELL,
    'ionocyte': MISCELLANEOUS,
    'keratinocyte': EPITHELIAL_CELL,
    'kidney cell': MISCELLANEOUS,
    'kidney collecting duct cell': MISCELLANEOUS,
    'kidney collecting duct intercalated cell': MISCELLANEOUS,
    'kidney collecting duct principal cell': MISCELLANEOUS,
    'kidney connecting tubule epithelial cell': MISCELLANEOUS,
    'kidney connecting tubule principal cell': MISCELLANEOUS,
    'kidney distal convoluted tubule epithelial cell': MISCELLANEOUS,
    'kidney epithelial cell': MISCELLANEOUS,
    'kidney interstitial fibroblast': FIBROBLAST,
    'kidney loop of Henle ascending limb epithelial cell': MISCELLANEOUS,
    'kidney loop of Henle epithelial cell': MISCELLANEOUS,
    'kidney loop of Henle thick ascending limb epithelial cell': EPITHELIAL_CELL,
    'kidney loop of Henle thin ascending limb epithelial cell': EPITHELIAL_CELL,
    'kidney loop of Henle thin descending limb epithelial cell': EPITHELIAL_CELL,
    'L2/3-6 intratelencephalic projecting glutamatergic cortical neuron': NEURON,
    'L5 extratelencephalic projecting glutamatergic cortical neuron': NEURON,
    'L6b glutamatergic cortical neuron': NEURON,
    'lamp5 GABAergic cortical interneuron': NEURON,
    'large pre-B-II cell': B_CELL,
    'late pro-B cell': B_CELL,
    'leukocyte': MISCELLANEOUS,
    'lung ciliated cell': EPITHELIAL_CELL,
    'lung macrophage': MACROPHAGE,
    'lung microvascular endothelial cell': ENDOTHELIAL,
    'lung neuroendocrine cell': MISCELLANEOUS,
    'lung pericyte': MISCELLANEOUS,
    'lymphocyte': MISCELLANEOUS,
    'macrophage': MACROPHAGE,
    'mammary alveolar cell': MISCELLANEOUS,
    'mast cell': MISCELLANEOUS,
    'mature B cell': B_CELL,
    'mature NK T cell': NK_CELL,
    'megakaryocyte': MISCELLANEOUS,
    'megakaryocyte-erythroid progenitor cell': MISCELLANEOUS,
    'melanocyte': MISCELLANEOUS,
    'memory B cell': B_CELL,
    'Merkel cell': MISCELLANEOUS,
    'mesangial cell': MISCELLANEOUS,
    'mesenchymal cell': CONNECTIVE_TISSUE_CELL,
    'mesenchymal stem cell': MISCELLANEOUS,
    'mesothelial cell': MISCELLANEOUS,
    'MHC-II-positive classical monocyte': MONOCYTE,
    'microglial cell': MISCELLANEOUS,
    'monocyte': MONOCYTE,
    'mucosal invariant T cell': T_CELL,
    'mucus secreting cell': MISCELLANEOUS,
    'multi-ciliated epithelial cell': EPITHELIAL_CELL,
    'mural cell': MISCELLANEOUS,
    'myelocyte': MISCELLANEOUS,
    'myeloid cell': MISCELLANEOUS,
    'myofibroblast cell': FIBROBLAST,
    'naive B cell': B_CELL,
    'naive thymus-derived CD4-positive, alpha-beta T cell': T_CELL,
    'naive thymus-derived CD8-positive, alpha-beta T cell': T_CELL,
    'nasal mucosa goblet cell': EPITHELIAL_CELL,
    'native cell': MISCELLANEOUS,
    'natural killer cell': NK_CELL,
    'near-projecting glutamatergic cortical neuron': NEURON,
    'neural cell': MISCELLANEOUS,
    'neuron': NEURON,
    'neutrophil': MISCELLANEOUS,
    'non-classical monocyte': MONOCYTE,
    'oligodendrocyte': GLIAL_CELL,
    'oligodendrocyte precursor cell': GLIAL_CELL,
    'pancreatic A cell': MISCELLANEOUS,
    'pancreatic acinar cell': MISCELLANEOUS,
    'pancreatic D cell': MISCELLANEOUS,
    'pancreatic ductal cell': MISCELLANEOUS,
    'pancreatic epsilon cell': MISCELLANEOUS,
    'pancreatic PP cell': MISCELLANEOUS,
    'pancreatic stellate cell': MISCELLANEOUS,
    'parietal epithelial cell': EPITHELIAL_CELL,
    'pericyte': MISCELLANEOUS,
    'placental villous trophoblast': MISCELLANEOUS,
    'plasma cell': PLASMA_CELL,
    'plasmablast': MISCELLANEOUS,
    'plasmacytoid dendritic cell': DENDRITIC_CELL,
    'platelet': MISCELLANEOUS,
    'podocyte': MISCELLANEOUS,
    'PP cell': MISCELLANEOUS,
    'pre-conventional dendritic cell': DENDRITIC_CELL,
    'primordial germ cell': MISCELLANEOUS,
    'pro-B cell': B_CELL,
    'professional antigen presenting cell': DENDRITIC_CELL,
    'progenitor cell of mammary luminal epithelium': MISCELLANEOUS,
    'promonocyte': MONOCYTE,
    'promyelocyte': MISCELLANEOUS,
    'pulmonary artery endothelial cell': ENDOTHELIAL,
    'pulmonary ionocyte': MISCELLANEOUS,
    'pvalb GABAergic cortical interneuron': NEURON,
    'regular atrial cardiac myocyte': MISCELLANEOUS,
    'regular ventricular cardiac myocyte': MISCELLANEOUS,
    'regulatory T cell': T_CELL,
    'renal alpha-intercalated cell': MISCELLANEOUS,
    'renal beta-intercalated cell': MISCELLANEOUS,
    'renal interstitial pericyte': MISCELLANEOUS,
    'renal principal cell': MISCELLANEOUS,
    'respiratory basal cell': MISCELLANEOUS,
    'respiratory goblet cell': EPITHELIAL_CELL,
    'respiratory hillock cell': MISCELLANEOUS,
    'Schwann cell': GLIAL_CELL,
    'serous cell of epithelium of bronchus': MISCELLANEOUS,
    'serous secreting cell': MISCELLANEOUS,
    'skeletal muscle satellite cell': SATELLITE,
    'small pre-B-II cell': B_CELL,
    'smooth muscle cell': SMOOOTH_MUSCLE,
    'sncg GABAergic cortical interneuron': NEURON,
    'sst GABAergic cortical interneuron': NEURON,
    'stromal cell': MISCELLANEOUS,
    'syncytiotrophoblast cell': MISCELLANEOUS,
    'T cell': T_CELL,
    'T-helper 17 cell': T_CELL,
    'tracheobronchial goblet cell': EPITHELIAL_CELL,
    'tracheobronchial serous cell': MISCELLANEOUS,
    'tracheobronchial smooth muscle cell': SMOOOTH_MUSCLE,
    'trophoblast giant cell': MISCELLANEOUS,
    'type B pancreatic cell': MISCELLANEOUS,
    'type I NK T cell': NK_CELL,
    'type I pneumocyte': MISCELLANEOUS,
    'type II pneumocyte': MISCELLANEOUS,
    'unswitched memory B cell': B_CELL,
    'uterine smooth muscle cell': SMOOOTH_MUSCLE,
    'vasa recta ascending limb cell': MISCELLANEOUS,
    'vasa recta descending limb cell': MISCELLANEOUS,
    'vascular associated smooth muscle cell': SMOOOTH_MUSCLE,
    'vascular leptomeningeal cell': MISCELLANEOUS,
    'vascular lymphangioblast': MISCELLANEOUS,
    'vein endothelial cell': ENDOTHELIAL,
    'vip GABAergic cortical interneuron': NEURON
}
